name: 'OpenAPI Lint Action'
description: 'Use OpenAPI Linter in GitHub Actions'
author: 'nwestfall'
inputs:
  file:
    required: false
    description: ./openapi3.yaml
  github_token:
    required: false
    description: ${{ secrets.GITHUB_TOKEN }}
