name: "Build Docker Image"
description: "Builds a Docker image"
inputs:
  context:
    description: "Path to the Docker build context"
    required: false
    default: "."
  repository:
    description: "Repository name for the Docker image (defaults to current GitHub repository)"
    required: false
    default: $(basename "${{ github.repository }}")
  domain:
    description: "The image's domain"
    required: true
  registry:
    description: "Azure Registry to authenticate against"
    required: true
  tag:
    description: "Tag for the Docker image"
    required: false
    default: ${{ github.ref_name }}
outputs:
  docker_image_name:
    description: "The name of the Docker image"
    value: ${{ steps.set_image_name_and_tag.outputs.docker_image_name }}
  docker_image_tag:
    description: "The version of the Docker image"
    value: ${{ steps.set_image_name_and_tag.outputs.docker_image_tag }}
  docker_image_full_name:
    description: "The version of the Docker image"
    value: ${{ steps.set_image_name_and_tag.outputs.docker_image_full_name }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Docker image name and tag
      id: set_image_name_and_tag
      run: |
        DOCKER_IMAGE_TAG="${{ inputs.tag }}"
        DOCKER_IMAGE_NAME="${{ inputs.registry }}/${{ inputs.domain }}/${{ inputs.repository }}"
        echo "docker_image_name=${{ inputs.repository }}" >> $GITHUB_OUTPUT
        echo "docker_image_full_name=$DOCKER_IMAGE_NAME" >> $GITHUB_OUTPUT
        echo "docker_image_tag=$DOCKER_IMAGE_TAG" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build the docker image
      run: docker build ${{ inputs.context }} -t ${{ steps.set_image_name_and_tag.outputs.docker_image_full_name }}:${{ steps.set_image_name_and_tag.outputs.docker_image_tag }}
      shell: bash
