name: "Build and Push Helm Chart"
description: "Builds and publishes a Helm chart to the specified registry."
inputs:
  scope:
    description: "Scope or namespace for the Helm chart."
    required: true
    default: ""
  context:
    description: "Path to the helm directory."
    required: true
    default: "./helm"
  registry:
    description: "Azure Registry to authenticate against."
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout helm chart repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Helm
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
      with:
        version: "v3.12.0"

    - name: Package chart into tgz file
      id: package_chart
      run: |
        PACKAGE_OUTPUT=$(helm package . --dependency-update)
        PACKAGE_FILE=$(echo "$PACKAGE_OUTPUT" | awk -F ': ' '/Successfully packaged chart and saved it to:/ {print $2}')
        echo "package_file=$PACKAGE_FILE" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.context }}
      shell: bash

    - name: Debug output filename
      run: |
        echo "Packaged chart file: ${{ steps.package_chart.outputs.package_file }}"
      shell: bash

    - name: Publish chart to ACR
      run: |
        helm push "${{ steps.package_chart.outputs.package_file }}" \
          oci://${{ inputs.registry }}/helm/${{ inputs.scope }}
      shell: bash
