name: "Build and Push Helm Chart"
description: "Builds and publishes a Helm chart to the specified registry."

inputs:
  domain:
    description: "The chart's domain."
    required: true
  context:
    description: "Path to the helm directory."
    required: false
    default: "./helm"
  registry:
    description: "Azure Registry to authenticate against."
    required: true
outputs:
  chart:
    description: "The name of the chart."
    value: ${{ steps.set_chart_name.outputs.chart }}
  ver:
    description: "The version of the chart."
    value: ${{ steps.set_chart_version.outputs.ver }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Helm
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
      with:
        version: "v3.12.0"

    - name: Get the chart's name
      id: chart_name
      run: |
        CHART=$(grep '^name:' Chart.yaml | awk '{print $2}')
        echo "chart=$CHART" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.context }}
      shell: bash

    - name: Get chart's version
      id: chart_version
      run: |
        VER=$(grep '^version:' Chart.yaml | awk '{print $2}')
        echo "ver=$VER" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.context }}
      shell: bash

    - name: Package chart into tgz file
      run: |
        helm package . --dependency-update
      working-directory: ${{ inputs.context }}
      shell: bash

    - name: Publish chart to ACR
      run: |
        helm push "${{ steps.chart_name.outputs.chart }}-${{ steps.chart_version.outputs.ver }}.tgz" oci://${{ inputs.registry }}/helm/${{ inputs.domain }}
      working-directory: ${{ inputs.context }}
      shell: bash
