name: "Build and Push Helm Chart"
description: "Builds and publishes a Helm chart to the specified registry."
inputs:
  domain:
    description: "The chart's domain."
    required: true
  context:
    description: "Path to the helm directory."
    required: false
    default: "./helm"
  registry:
    description: "Azure Registry to authenticate against."
    required: true
outputs:
  chart:
    description: "The name of the chart."
  ver:
    description: "The version of the chart."

runs:
  using: "composite"
  steps:
    - name: Checkout helm chart repository
      uses: actions/checkout@v4

    - name: Setup Helm
      uses: azure/setup-helm@v3.5
      with:
        version: "v3.12.0"

    - name: Get chart's name
      id: set_chart_name
      run: |
        CHART=$(grep '^name:' Chart.yaml | awk '{print $2}')
        echo "chart=$CHART" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.context }}
      shell: bash

    - name: Get chart's version
      id: set_chart_version
      run: |
        VER=$(grep '^version:' Chart.yaml | awk '{print $2}')
        echo "ver=$VER" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.context }}
      shell: bash

    - name: Package chart into tgz file
      run: |
        helm package . --dependency-update
      working-directory: ${{ inputs.context }}
      shell: bash

    - name: Publish chart to ACR
      run: |
        helm push "${{ steps.set_chart_name.outputs.chart }}-${{ steps.set_chart_version.outputs.ver }}.tgz" oci://${{ inputs.registry }}/helm/${{ inputs.domain }}
      working-directory: ${{ inputs.context }}
      shell: bash
