name: "Push Docker Image"
description: "Pushes a previously built Docker image."
inputs:
  image_name:
    description: "Name of the Docker image to push, including the registry and repository (e.g., 'myregistry.azurecr.io/myrepo/myimage')"
    required: true
  image_tag:
    description: "Tag of the Docker image to push"
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Push docker image
      run: docker push ${{ inputs.image_name }}:${{ inputs.image_tag }}
      shell: bash
