name: "Update Artifacts File"
description: "An action to update the artifacts file in a different repository"

env:
  TARGET_PATH: temp_helm_charts

inputs:
  domain:
    description: "Domain or namespace for the artifact."
    required: true
  registry:
    description: "Registry to push the artifact to."
    required: true
  type:
    description: "Artifact type"
    required: true
  artifact_name:
    description: "Artifact name"
    required: true
  artifact_tag:
    description: "Artifact tag"
    required: true
  github_token:
    description: "GitHub token with access to target repository"
    required: true
  target_repo:
    description: "Target GitHub repository"
    required: false
    default: "mapcolonies/helm-charts"

runs:
  using: "composite"
  steps:
    - name: Checkout helm chart repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{ inputs.target_repo }}
        token: ${{ inputs.github_token }}
        path: $TARGET_PATH

    - name: Set execute permission on modify script
      run: chmod +x actions/update-artifacts-file/modify_artifacts.sh
      shell: bash

    - name: Run modify artifacts script
      run: actions/update-artifacts-file/modify_artifacts.sh
      shell: bash
      env:
        DOMAIN: ${{ inputs.domain }}
        ARTIFACT_NAME: ${{ inputs.artifact_name }}
        ARTIFACT_TAG: ${{ inputs.artifact_tag }}
        TYPE: ${{ inputs.type }}
        REGISTRY: ${{ inputs.registry }}
        TARGET_DIR: $TARGET_PATH

    - name: Set execute permission on commit script
      run: chmod +x actions/update-artifacts-file/commit_changes.sh
      shell: bash

    - name: Commit and push changes
      run: actions/update-artifacts-file/commit_changes.sh
      shell: bash
      env:
        DOMAIN: ${{ inputs.domain }}
        ARTIFACT_NAME: ${{ inputs.artifact_name }}
        ARTIFACT_TAG: ${{ inputs.artifact_tag }}
        TYPE: ${{ inputs.type }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TARGET_REPO: ${{ inputs.target_repo }}
        TARGET_DIR: $TARGET_PATH

    - name: Clean up target repo folder
      run: rm -rf $TARGET_PATH
      shell: bash
