name: "Update Artifacts File"
description: "An action to update the artifacts file in a different repository"

env:
  TARGET_PATH: temp_repo

inputs:
  domain:
    description: "Domain or namespace for the artifact."
    required: true
  registry:
    description: "Registry to push the artifact to."
    required: true
  type:
    description: "Artifact type"
    required: true
  artifact_name:
    description: "Artifact name"
    required: true
  artifact_tag:
    description: "Artifact tag"
    required: true
  github_token:
    description: "GitHub token with access to target repository"
    required: true
  target_repo:
    description: "Target GitHub repository"
    required: false
    default: "mapcolonies/helm-charts"
  target_branch:
    description: "Target branch in the repository to update"
    required: false
    default: "master"

runs:
  using: "composite"
  steps:
    - name: Checkout helm chart repository
      uses: actions/checkout@v5
      with:
        repository: ${{ inputs.target_repo }}
        token: ${{ inputs.github_token }}
        path: $TARGET_PATH
        ref: ${{ inputs.target_branch }}

    - name: Run modify artifacts script
      run: ${{ github.action_path }}/modify_artifacts.sh
      shell: bash
      env:
        DOMAIN: ${{ inputs.domain }}
        ARTIFACT_NAME: ${{ inputs.artifact_name }}
        ARTIFACT_TAG: ${{ inputs.artifact_tag }}
        TYPE: ${{ inputs.type }}
        REGISTRY: ${{ inputs.registry }}
        TARGET_PATH: $TARGET_PATH

    - name: Commit and push changes
      run: ${{ github.action_path }}/commit_changes.sh
      shell: bash
      env:
        DOMAIN: ${{ inputs.domain }}
        ARTIFACT_NAME: ${{ inputs.artifact_name }}
        ARTIFACT_TAG: ${{ inputs.artifact_tag }}
        TYPE: ${{ inputs.type }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TARGET_REPO: ${{ inputs.target_repo }}
        TARGET_PATH: $TARGET_PATH
        TARGET_BRANCH: ${{ inputs.target_branch }}

    - name: Clean up target repo folder
      run: rm -rf $TARGET_PATH
      shell: bash
