name: "Artifactory Login"
description: "Logs into the Artifactory registry."
inputs:
  registry:
    description: Azure Registry to authenticate against.
    required: true
  username:
    description: Azure Registry username.
    required: true
  password:
    description: Azure Registry password.
    required: true

runs:
  using: composite
  steps:
    - name: Login to registry
      uses: azure/docker-login@15c4aadf093404726ab2ff205b2cdd33fa6d054c # v2
      with:
        login-server: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
