name: validate-domain
description: "Validate that helm/Chart.yaml contains annotations.domain with an allowed value"

inputs:
  chart-file:
    description: "Path to Chart.yaml"
    required: false
    default: "helm/Chart.yaml"
  allowed-domains:
    description: "List of allowed domain values"
    required: false
    default: |
      - raster
      - vector
      - infra
      - 3d
      - app
      - dem
      - common

runs:
  using: composite
  steps:
    - name: Read domain annotation from Chart.yaml
      id: get_domain
      uses: mikefarah/yq@v4.44.1
      with:
        cmd: yq e '.annotations.domain' "${{ inputs.chart-file }}"

    - name: Validate domain
      shell: bash
      run: |
        DOMAIN="${{ steps.get_domain.outputs.result }}"
        allowed=(${{ toJson(inputs.allowed-domains) }})

        printf "%s\n" "${allowed[@]}" | grep -qx "$DOMAIN" \
          || { echo "Invalid domain: $DOMAIN"; exit 1; }
