name: init-npm
description: 'Initialize the repo with npm and install all the dependencies'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22.x'
  path:
    description: "Path to the Node.js directory"
    default: "."
    required: false
runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.path }}/package-lock.json

    - name: Install TS Project dependencies
      shell: bash
      run: npm ci
      working-directory: ${{ inputs.path }}

    - name: build
      shell: bash
      run: npm run build
      working-directory: ${{ inputs.path }}
