name: "Run ESLint"
description: "Installs dependencies and runs ESLint"
inputs:
  node-version:
    description: "Node.js version"
    default: "20"
    required: false
  path:
    description: "Path to the Node.js dir "
    default: "."
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout helm chart repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Node.js
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
      with:
        node-version: ${{ inputs['node-version'] }}

    - run: npm install
      shell: bash
      working-directory: ${{ inputs.path }}

    - run: npm ci
      shell: bash
      working-directory: ${{ inputs.path }}

    - run: npm run lint
      shell: bash
      working-directory: ${{ inputs.path }}
