name: Action Lint

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  action-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: actionlint
        uses: devops-actions/actionlint@v0.1.3
