name: Action Lint

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  action-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: actionlint
        uses: reviewdog/action-actionlint@v1.65.2
        with:
          github_token: ${{ secrets.GH_PAT }}
          reporter: github-pr-check
          fail_level: error
          actionlint_flags: ".github/workflows/*.yml .github/workflows/*.yaml"
