name: reviewdog
on: [pull_request]
jobs:
  actionlint-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build actionlint flags
        id: build_flags
        run: |
          files="$(find actions -type f \( -name '*.yml' -o -name '*.yaml' \) | paste -sd' ' -)"
          # shellcheck disable=SC2086
          echo "flags=$files" >> $GITHUB_OUTPUT
      - uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281 # v1.65.2
        with:
          github_token: ${{ secrets.GH_PAT }}
          reporter: github-pr-review
          actionlint_flags: ${{ steps.build_flags.outputs.flags }}
          fail_level: error
