name: Action Lint

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  action-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: actionlint
        uses: raven-actions/actionlint@v2
        with:
          files: ".github/workflows/*.yml, .github/workflows/*.yaml, actions/**/*.yml, actions/**/*.yaml"
