name: Match chart version and push to registry

on:
  workflow_call:

env:
  HELM_EXPERIMENTAL_OCI: 1

permissions:
  contents: write
  pull-requests: write

jobs:
  build_and_push_helm:
    name: Build and publish helm package to registry
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout repository from latest commit
        uses: actions/checkout@v2

      - name: Setup helm
        uses: azure/setup-helm@v3.5
        with:
          version: 'v3.12.0'

      - name: Login to registry
        run: |
          helm registry login ${{ secrets.ACR_URL }} --username ${{ secrets.ACR_PUSH_USER }} --password ${{ secrets.ACR_PUSH_TOKEN }} 

      - name: Get chart's name
        run: |
          export "CHART=$(cat Chart.yaml | grep name | awk '{print $2; exit}')"
          echo "CHART=$CHART" >> $GITHUB_ENV
        working-directory: ./helm

      - name: Get chart's version 
        run: |
          export "VER=$(cat Chart.yaml | grep version | awk '{print $2; exit}')"
          echo "VER=$VER" >> $GITHUB_ENV
        working-directory: ./helm    

      - name: Package chart into tgz file
        run: |
          helm package . --dependency-update 
        working-directory: ./helm

      - name: Publish chart to ACR
        run: |
          helm push ${{ env.CHART }}-${{ env.VER }}.tgz oci://${{ secrets.ACR_URL }}/helm
        working-directory: ./helm
