name: Lint Commit Messages
on: [push] 

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
        #   ref: add-commitlint
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
