name: Lint and Test Charts

on:
  workflow_call:
    inputs:
      chartDirs:
        description: "The root dir or dirs (separated with commas)"
        type: string
        required: false
        default: "."

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Shared Workflows repository
        uses: actions/checkout@v4
        with:
          repository: MapColonies/shared-workflows
          path: shared-workflows
          token: ${{ secrets.GH_PAT }}

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.16.3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs ${{ inputs.chartDirs }} --target-branch ${{ github.event.repository.default_branch }} --config shared-workflows/.github/configs/ct.yaml)
          echo "changed=$changed"
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Helm registry login
        run: >
          helm registry login ${{ secrets.ACR_URL }}
          --username ${{ secrets.ACR_PUSH_USER }}
          --password ${{ secrets.ACR_PUSH_TOKEN }}

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: > 
          ct lint 
          --chart-dirs ${{ inputs.chartDirs }} 
          --target-branch ${{ github.event.repository.default_branch }} 
          --config shared-workflows/.github/configs/ct.yaml 
          --lint-conf shared-workflows/.github/configs/lintconf.yaml
