
name: Github Readme Generator

on:
  push:
    branches:    
      - '*'

permissions:
  contents: write
  pull-requests: write

jobs:
  build_and_push_docker:
    name: Build and publish docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository from latest commit
        uses: actions/checkout@v2

      - name: Generate readme
        uses: bitflight-devops/github-action-readme-generator@v1.8.0
        with:
          action: "action.yml"
          readme: "README.md"
