name: Github Readme Generator

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  build_and_push_docker:
    name: Build and publish docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository from latest commit
        uses: bitflight-devops/github-action-readme-generator@v1.7.2
