name: Slash Command Dispatch

on:
  workflow_call:

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: resolve pr refs
        id: refs
        uses: eficode/resolve-pr-refs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Checkout pull request branch
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ${{ steps.refs.outputs.base_ref }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Slash Command Dispatch
        id: scd
        uses: peter-evans/slash-command-dispatch@v4
        with:
          ref: ${{ steps.refs.outputs.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: |
            postgis-check
          dispatch-type: workflow
          static-args: |
            issue-number=${{ github.event.issue.number }}
            comment-creation-date=${{ github.event.comment.created_at }}
      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.scd.outputs.error-message }}
