name: Publish npm Package

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master
    paths:
      - "actions/npm-publish/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test Publish Package
        uses: ./actions/npm-publish
        with:
          node-version: ${{ inputs.node-version }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          path: ./test
