name: Init-npm repository

on:
  pull_request:
    paths:
      - "actions/init-npm/**"

jobs:
  test-init-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test init-npm action
        uses: ./actions/init-npm
        with:
          node-version: '20.x'
          path: ./test
