name: Helm Lint repository

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master
    paths:
      - "actions/helm-lint/**"
      
permissions:
  contents: write
  id-token: write

jobs:
  test-helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: helm lint
        uses: ./actions/helm-lint
        with:
          repository: ${{ github.repository }}
          chartDirs: "./infra/test-helm"
