name: Helm Lint repository

on:
  pull_request:
    paths:
      - "actions/helm-lint/**"
      
permissions:
  contents: write
  id-token: write

jobs:
  test-helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: helm lint
        uses: ./actions/helm-lint
        id: helm-lint
        with:
          repository: ${{ github.repository }}
          chartDirs: "./test/helm"

      - name: Print on chart change
        if: steps.helm-lint.outputs.changed == 'true'
        run: echo "Charts were changed and linted."
