name: esint repository

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master
    paths:
      - "actions/eslint/**"

jobs:
  test-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: eslint
        uses: ./actions/eslint
        with:
          path: ./test
