name: Test OpenApi-lint

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - "actions/opanapi-lint/**"

jobs:
  test-openapi-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: openapi-lint
        uses: ./actions/openapi-lint
        with:
          path: ./test
