name: Test Build and Push Helm Chart

on:
  pull_request:
    paths:
      - "actions/build-and-push-helm/**"
      
jobs:
  test-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_PUSH_USER }}
          password: ${{ secrets.ACR_PUSH_TOKEN }}

      - name: Test Build and push Helm Chart
        uses: ./actions/build-and-push-helm
        with:
          context: ./test/helm
          domain: infra
          registry: ${{ secrets.ACR_URL }}
